# 一、 ndarray
## 1.ndarray的特性
### 多维性


In [271]:
import numpy as np

In [272]:
arr = np.array(5)   #创建零维ndarray数组，即常量
print(arr)
print(f'arr的维度：{arr.ndim}')     #获取维度

5
arr的维度：0


In [273]:
arr = np.array([1, 2, 3])   #创建零维ndarray数组，即常量
print(arr)
print(f'arr的维度：{arr.ndim}')     #获取维度

[1 2 3]
arr的维度：1


In [274]:
arr = np.array([[1, 2, 3], [4, 5, 6]])   #创建零维ndarray数组，即常量
print(arr)
print(f'arr的维度：{arr.ndim}')     #获取维度

[[1 2 3]
 [4 5 6]]
arr的维度：2


### 同质性

In [275]:
arr = np.array([1, 'hello'])    #不同数据类型会自动转换为相同类型
print(arr)

['1' 'hello']


In [276]:
arr = np.array([1, 2.5])    #不同数据类型会自动转换为相同类型
print(arr)

[1.  2.5]


## 2.ndarray的属性

In [277]:
arr = np.array(1)
print(arr)
print(f'arr的形状：{arr.shape}')    #几行几列
print(f'arr的维度：{arr.ndim}')
print(f'元素个数：{arr.size}')
print(f'元素类型：{arr.dtype}')
print(f'元素转置：{arr.T}')
print(f'单元素占用字节数：{arr.itemsize}')
print(f'数组总占用字节数：{arr.nbytes}')
print(f'内存存储方式(是否连续)：\n{arr.flags}')

1
arr的形状：()
arr的维度：0
元素个数：1
元素类型：int64
元素转置：1
单元素占用字节数：8
数组总占用字节数：8
内存存储方式(是否连续)：
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [278]:
arr = np.array([1, 2, 3])
print(arr)
print(f'arr的形状：{arr.shape}')
print(f'arr的维度：{arr.ndim}')
print(f'元素个数：{arr.size}')
print(f'元素类型：{arr.dtype}')
print(f'元素转置：{arr.T}')
print(f'单元素占用字节数：{arr.itemsize}')
print(f'数组总占用字节数：{arr.nbytes}')
print(f'内存存储方式(是否连续)：\n{arr.flags}')

[1 2 3]
arr的形状：(3,)
arr的维度：1
元素个数：3
元素类型：int64
元素转置：[1 2 3]
单元素占用字节数：8
数组总占用字节数：24
内存存储方式(是否连续)：
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [279]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(f'arr的形状：{arr.shape}')
print(f'arr的维度：{arr.ndim}')
print(f'元素个数：{arr.size}')
print(f'元素类型：{arr.dtype}')
print(f'元素转置：\n{arr.T}')
print(f'单元素占用字节数：{arr.itemsize}')
print(f'数组总占用字节数：{arr.nbytes}')
print(f'内存存储方式(是否连续)：\n{arr.flags}')

[[1 2 3]
 [4 5 6]]
arr的形状：(2, 3)
arr的维度：2
元素个数：6
元素类型：int64
元素转置：
[[1 4]
 [2 5]
 [3 6]]
单元素占用字节数：8
数组总占用字节数：48
内存存储方式(是否连续)：
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



## 3.ndarray的创建

In [280]:
# 基础创建方法
list = [1, 2, 3]
arr = np.array(list, dtype=np.float64)    #其实是传入一个列表,还可以指定类型
print(arr)

[1. 2. 3.]


In [281]:
# copy方法
arr1 = np.copy(arr)
print(arr1)

[1. 2. 3.]


### 预定义形状

In [282]:
# 全0
arr = np.zeros((2, 3))  #传入一个shape类型，(元组),创建一个全0的2行3列矩阵
print(arr)
print(f'默认类型：{arr.dtype}')

[[0. 0. 0.]
 [0. 0. 0.]]
默认类型：float64


In [283]:
# 全1
arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [284]:
# 未初始化
arr = np.empty((3, 3))
print(arr)

[[4.9e-324 0.0e+000 0.0e+000]
 [0.0e+000 9.9e-324 0.0e+000]
 [0.0e+000 0.0e+000 1.5e-323]]


In [285]:
# 固定值
arr = np.full((2, 3), 5)
print(arr)

[[5 5 5]
 [5 5 5]]


In [286]:
# 模仿
# 最新一次的arr是2行3列的矩阵
arr2 = np.zeros_like(arr)   #模仿arr的形状，生成全0
print(arr2)
arr2 = np.ones_like(arr)    #模仿arr的形状，生成全1
print(arr2)
arr2 = np.full_like(arr, 8) #模仿arr的形状，生成全8
print(arr2)
arr2 = np.empty_like(arr)   #模仿arr的形状，生成全随机
print(arr2)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[8 8 8]
 [8 8 8]]
[[1 1 1]
 [1 1 1]]


In [287]:
# 按步长
arr = np.arange(0, 10, 2)   #和range类似，左闭右开，步长为2
print(arr)

[0 2 4 6 8]


In [288]:
# 按数量取区间等间距
arr = np.linspace(0, 100, 5)     #此处左右闭合，等间距取5个数
print(arr)

[  0.  25.  50.  75. 100.]


In [289]:
# 对数步长
arr = np.logspace(0, 4, 3, base=2)
# 0  1  2  3  4
# ^     ^     ^
# 0到4之间取3个数，基底为2
#log2(1) = 0, log2(4) = 2, log2(16) = 4
print(arr)
# 其实最终得到的是等比数列

[ 1.  4. 16.]


In [290]:
# 再演示一个
arr = np.logspace(1, 5, 5, base=10)
print(arr)
#得到的就是1，10，100，1000，10000

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]


In [291]:
# 特殊矩阵
# 单位矩阵：主对角线上数字为1，其他数字为0
arr = np.eye(3, 4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [292]:
# 对角矩阵：主对角线非0，其他数字为0
arr = np.diag([1, 2, 3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [293]:
# 随机数组生成
# 生成0，1之间的随机浮点数
arr = np.random.rand(2, 3)
print(arr)

[[0.32920641 0.51064106 0.26362883]
 [0.31051155 0.62685344 0.55744981]]


In [294]:
# 生成区间随机浮点数
arr = np.random.uniform(1, 100, (2, 3))
print(arr)

[[32.5393764  40.08947886 26.539484  ]
 [58.64187121 17.00124233 60.21524816]]


In [295]:
# 生成区间随机整数数
arr = np.random.randint(1, 100, (2, 3))
print(arr)

[[11 34 86]
 [18 41 83]]


In [296]:
# 生成区间随机浮点数 （正态分布）
arr = np.random.randn(2, 3)
print(arr)

[[0.64703408 0.59321721 0.4380245 ]
 [1.35778902 1.20451128 1.35179619]]


In [297]:
# 设置随机数种子
np.random.seed(20)
arr = np.random.randint(1, 10, (2, 3))
print(arr)

[[4 5 7]
 [8 3 1]]


## 4. ndarray的数据类型

布尔类型 bool

整数类型 int uint   8~64位

浮点数 float   16~64位

复数 complex  32~64位

In [298]:
# 布尔类型
arr = np.array([1, 0, 2, 0], dtype = 'bool')
print(arr)

[ True False  True False]


In [299]:
# 整形
arr = np.array([1, 2, 3, 127], dtype = np.int8)
print(arr)

[  1   2   3 127]


## 5.索引与切片

### 一维数组的索引与切片

In [300]:
# 生成20个1~100随机整数
arr = np.random.randint(1, 100, 20)
print(arr)

[41 86 91 27 84 17 63 17  8 99  7 27 14 76 59 26  4 75 76 62]


In [301]:
print(arr[0], arr[1], arr[2])

41 86 91


In [302]:
print(arr[:3])  #前3个
print(arr[3:])  #3个之后的所有

[41 86 91]
[27 84 17 63 17  8 99  7 27 14 76 59 26  4 75 76 62]


In [303]:
print(arr[:-3])     #除去后3个
print(arr[-3:])     #后3个

[41 86 91 27 84 17 63 17  8 99  7 27 14 76 59 26  4]
[75 76 62]


In [304]:
print(arr[3:5])     #下标3~5之间两个，左闭右开

[27 84]


In [305]:
print(arr[5:3])     #反向索引为空

[]


In [306]:
print(arr[(arr > 50) & (arr < 80)])     #大于50小于80的元素

[63 76 59 75 76 62]


In [307]:
print(arr[slice(3, 5)])     #等价[3:5]
print(arr[slice(0, 20, 2)])     #0~20个元素之间，步长为2

[27 84]
[41 91 84 63  8  7 14 59  4 76]


### 二维数组的索引与切片

In [314]:
arr = np.random.randint(1, 100, (5, 5))     #1到100的5行5列的随机整数
print(arr)

[[18 41 83 43 61]
 [85 31 37  9 49]
 [20 49 96 54 11]
 [39 10 61 61 24]
 [53 97 77 79 96]]


In [315]:
print(arr[2, 2])    #下标2，2

96


In [333]:
print(arr[1:2, :])      #行取1到2，左开右闭，列取所有

[[85 31 37  9 49]]


In [316]:
# 下标2行，前3列
print(arr[:2, :3],"\n")
# 下标2行，后3列
print(arr[1, 2:])

[[18 41 83]
 [85 31 37]] 

[37  9 49]


In [317]:
# 下标1行，后4位
print(arr[1, -4:])
print(arr[1, -4:][arr[1, -4:] > 10])      #取下标1行，后4位，并筛选大于10的元素

[31 37  9 49]
[31 37 49]


In [318]:
# 取列
print(arr[:, 2])    #取下标2列
print(arr[:, 2][arr[:, 2] > 50])

[83 37 96 61 77]
[83 96 61 77]


## 6.数组的运算

In [335]:
# 算术运算
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [337]:
c = [1, 2, 3]
d = [4, 5, 6]
print(c + d)    #普通列表相加
print(np.array(c) + np.array(d))    #numpy数组相加

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [341]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]


In [342]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9]])
print(a + b)    #矩阵相加,不满足矩阵大小一致，会报错

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [346]:
# 广播机制
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a + 1)    #矩阵每一个元素加1
print(a - 1)    #矩阵每一个元素减1
print(a * 2)    #矩阵每一个元素乘2
print(a / 2)    #矩阵每一个元素除2

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [355]:
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
# 维度1*3=3*1

# a做行扩展
# 1 2 3
# 1 2 3
# 1 2 3

# b做列扩展
# 4 4 4
# 5 5 5
# 6 6 6

# 互相做加减乘除

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[-3 -2 -1]
 [-4 -3 -2]
 [-5 -4 -3]]
[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]
[[0.25       0.5        0.75      ]
 [0.2        0.4        0.6       ]
 [0.16666667 0.33333333 0.5       ]]


In [364]:
# 矩阵运算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a @ b)

# 1 2 3
# 4 5 6
# 7 8 9

# 4 5 6
# 7 8 9
# 1 2 3

# 1 * 4 + 2 * 7 + 3 * 1 = 21
# 1 * 5 + 2 * 8 + 3 * 2 = 27
# 1 * 6 + 2 * 9 + 3 * 3 = 33

# 4 * 4 + 5 * 7 + 6 * 1 = 57
# 4 * 5 + 5 * 8 + 6 * 2 = 72
# 4 * 6 + 5 * 9 + 6 * 3 = 87

# 7 * 4 + 8 * 7 + 9 * 1 = 93
# 7 * 5 + 8 * 8 + 9 * 2 = 117
# 7 * 6 + 8 * 9 + 9 * 3 = 141

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]
