1.基本数学函数

In [6]:
import numpy as np
from IPython.core.tbtools import nullrepr

# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1, 4, 9]))
arr = np.array([1, 25, 81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [7]:
# 计算指数
print(np.exp(1))    #e^1

2.718281828459045


In [15]:
# 计算自然对数
print(np.log(np.e))     #ln(e)
print(np.log10(100))    #lg(100)
print(np.log2(8))       #log2(8)
# 换底要用换底公式：log_a(b) = log_c(b)/log_c(a)

1.0
2.0
3.0


In [21]:
# 计算正弦值、余弦值
print(np.sin(np.pi/2))      #sin(π/2)
print(np.cos(0))            #cos 0

1.0
1.0


In [24]:
# 计算绝对值
print(np.abs(-1))
print(np.abs([-1, -2, -3]))

1
[1 2 3]


In [26]:
# 计算次幂
print(np.power(2, 3))
print(np.power([1, 2, 3], 2))

8
[1 4 9]


In [35]:
# 四舍五入
print(np.round([1.2, 2.6, 3.5, 4.8]))

[1. 3. 4. 5.]


In [36]:
# 取整
print(np.floor([1.2, 2.6, 3.5, 4.8]))   # 向下取整
print(np.ceil([1.2, 2.6, 3.5, 4.8]))    # 向上取整

[1. 2. 3. 4.]
[2. 3. 4. 5.]


In [42]:
# 检测缺失值
np.isnan([1, np.nan, 2])

array([False,  True, False])