1.基本数学函数

In [1]:
import numpy as np
from IPython.core.tbtools import nullrepr

# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1, 4, 9]))
arr = np.array([1, 25, 81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [2]:
# 计算指数
print(np.exp(1))    #e^1

2.718281828459045


In [3]:
# 计算自然对数
print(np.log(np.e))     #ln(e)
print(np.log10(100))    #lg(100)
print(np.log2(8))       #log2(8)
# 换底要用换底公式：log_a(b) = log_c(b)/log_c(a)

1.0
2.0
3.0


In [4]:
# 计算正弦值、余弦值
print(np.sin(np.pi/2))      #sin(π/2)
print(np.cos(0))            #cos 0

1.0
1.0


In [5]:
# 计算绝对值
print(np.abs(-1))
print(np.abs([-1, -2, -3]))

1
[1 2 3]


In [6]:
# 计算次幂
print(np.power(2, 3))
print(np.power([1, 2, 3], 2))

8
[1 4 9]


In [7]:
# 四舍五入
print(np.round([1.2, 2.6, 3.5, 4.8]))

[1. 3. 4. 5.]


In [8]:
# 取整
print(np.floor([1.2, 2.6, 3.5, 4.8]))   # 向下取整
print(np.ceil([1.2, 2.6, 3.5, 4.8]))    # 向上取整

[1. 2. 3. 4.]
[2. 3. 4. 5.]


In [9]:
# 检测缺失值
np.isnan([1, np.nan, 2])

array([False,  True, False])

2.统计函数
求和，计算平均值，计算中位数，标准差，方差
查找最大最小值
计算分位数，累积和，累积积

In [15]:
arr = np.random.randint(1, 20, 8)
print(arr)

[18 16 12  9 17 11 12 16]


In [20]:
# 求和
print(np.sum(arr))
# 计算平均值
print(np.mean(arr))
print(np.average(arr))
# 计算中位数
print(np.median(arr))

111
13.875
13.875
14.0


In [21]:
# 方差
print(np.var(arr))
# 标准差
print(np.std(arr))

9.359375
3.059309562630104


In [25]:
print(arr)
# 最大值+索引
print(np.max(arr), np.argmax(arr))
# 最小值+索引
print(np.min(arr), np.argmin(arr))

[18 16 12  9 17 11 12 16]
18 0
9 3


In [33]:
# 分位数
print(arr)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.percentile(arr, 40))   # 75%分位数


[ 1  2  3  4  5  6  7  8  9 10]
4.6


In [35]:
# 累积和
print(np.cumsum(arr))
# 累积积
print(np.cumprod(arr))

[ 1  3  6 10 15 21 28 36 45 55]
[      1       2       6      24     120     720    5040   40320  362880
 3628800]


In [ ]:
# 