# 一、 ndarray
## 1.ndarray的特性
### 多维性


In [186]:
import numpy as np

In [187]:
arr = np.array(5)   #创建零维ndarray数组，即常量
print(arr)
print(f'arr的维度：{arr.ndim}')     #获取维度

5
arr的维度：0


In [188]:
arr = np.array([1, 2, 3])   #创建零维ndarray数组，即常量
print(arr)
print(f'arr的维度：{arr.ndim}')     #获取维度

[1 2 3]
arr的维度：1


In [189]:
arr = np.array([[1, 2, 3], [4, 5, 6]])   #创建零维ndarray数组，即常量
print(arr)
print(f'arr的维度：{arr.ndim}')     #获取维度

[[1 2 3]
 [4 5 6]]
arr的维度：2


### 同质性

In [190]:
arr = np.array([1, 'hello'])    #不同数据类型会自动转换为相同类型
print(arr)

['1' 'hello']


In [191]:
arr = np.array([1, 2.5])    #不同数据类型会自动转换为相同类型
print(arr)

[1.  2.5]


## 2.ndarray的属性

In [192]:
arr = np.array(1)
print(arr)
print(f'arr的形状：{arr.shape}')    #几行几列
print(f'arr的维度：{arr.ndim}')
print(f'元素个数：{arr.size}')
print(f'元素类型：{arr.dtype}')
print(f'元素转置：{arr.T}')
print(f'单元素占用字节数：{arr.itemsize}')
print(f'数组总占用字节数：{arr.nbytes}')
print(f'内存存储方式(是否连续)：\n{arr.flags}')

1
arr的形状：()
arr的维度：0
元素个数：1
元素类型：int64
元素转置：1
单元素占用字节数：8
数组总占用字节数：8
内存存储方式(是否连续)：
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [193]:
arr = np.array([1, 2, 3])
print(arr)
print(f'arr的形状：{arr.shape}')
print(f'arr的维度：{arr.ndim}')
print(f'元素个数：{arr.size}')
print(f'元素类型：{arr.dtype}')
print(f'元素转置：{arr.T}')
print(f'单元素占用字节数：{arr.itemsize}')
print(f'数组总占用字节数：{arr.nbytes}')
print(f'内存存储方式(是否连续)：\n{arr.flags}')

[1 2 3]
arr的形状：(3,)
arr的维度：1
元素个数：3
元素类型：int64
元素转置：[1 2 3]
单元素占用字节数：8
数组总占用字节数：24
内存存储方式(是否连续)：
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [194]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(f'arr的形状：{arr.shape}')
print(f'arr的维度：{arr.ndim}')
print(f'元素个数：{arr.size}')
print(f'元素类型：{arr.dtype}')
print(f'元素转置：\n{arr.T}')
print(f'单元素占用字节数：{arr.itemsize}')
print(f'数组总占用字节数：{arr.nbytes}')
print(f'内存存储方式(是否连续)：\n{arr.flags}')

[[1 2 3]
 [4 5 6]]
arr的形状：(2, 3)
arr的维度：2
元素个数：6
元素类型：int64
元素转置：
[[1 4]
 [2 5]
 [3 6]]
单元素占用字节数：8
数组总占用字节数：48
内存存储方式(是否连续)：
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



## 3.ndarray的创建

In [195]:
# 基础创建方法
list = [1, 2, 3]
arr = np.array(list, dtype=np.float64)    #其实是传入一个列表,还可以指定类型
print(arr)

[1. 2. 3.]


In [196]:
# copy方法
arr1 = np.copy(arr)
print(arr1)

[1. 2. 3.]


### 预定义形状

In [197]:
# 全0
arr = np.zeros((2, 3))  #传入一个shape类型，(元组),创建一个全0的2行3列矩阵
print(arr)
print(f'默认类型：{arr.dtype}')

[[0. 0. 0.]
 [0. 0. 0.]]
默认类型：float64


In [198]:
# 全1
arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [199]:
# 未初始化
arr = np.empty((3, 3))
print(arr)

[[4.9e-324 0.0e+000 0.0e+000]
 [0.0e+000 9.9e-324 0.0e+000]
 [0.0e+000 0.0e+000 1.5e-323]]


In [200]:
# 固定值
arr = np.full((2, 3), 5)
print(arr)

[[5 5 5]
 [5 5 5]]


In [201]:
# 模仿
# 最新一次的arr是2行3列的矩阵
arr2 = np.zeros_like(arr)   #模仿arr的形状，生成全0
print(arr2)
arr2 = np.ones_like(arr)    #模仿arr的形状，生成全1
print(arr2)
arr2 = np.full_like(arr, 8) #模仿arr的形状，生成全8
print(arr2)
arr2 = np.empty_like(arr)   #模仿arr的形状，生成全随机
print(arr2)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[8 8 8]
 [8 8 8]]
[[1 1 1]
 [1 1 1]]


In [202]:
# 按步长
arr = np.arange(0, 10, 2)   #和range类似，左闭右开，步长为2
print(arr)

[0 2 4 6 8]


In [203]:
# 按数量取区间等间距
arr = np.linspace(0, 100, 5)     #此处左右闭合，等间距取5个数
print(arr)

[  0.  25.  50.  75. 100.]


In [204]:
# 对数步长
arr = np.logspace(0, 4, 3, base=2)
# 0  1  2  3  4
# ^     ^     ^
# 0到4之间取3个数，基底为2
#log2(1) = 0, log2(4) = 2, log2(16) = 4
print(arr)
# 其实最终得到的是等比数列

[ 1.  4. 16.]


In [205]:
# 再演示一个
arr = np.logspace(1, 5, 5, base=10)
print(arr)
#得到的就是1，10，100，1000，10000

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]


In [206]:
# 特殊矩阵
# 单位矩阵：主对角线上数字为1，其他数字为0
arr = np.eye(3, 4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [207]:
# 对角矩阵：主对角线非0，其他数字为0
arr = np.diag([1, 2, 3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [208]:
# 随机数组生成
# 生成0，1之间的随机浮点数
arr = np.random.rand(2, 3)
print(arr)

[[0.32920641 0.51064106 0.26362883]
 [0.31051155 0.62685344 0.55744981]]


In [209]:
# 生成区间随机浮点数
arr = np.random.uniform(1, 100, (2, 3))
print(arr)

[[32.5393764  40.08947886 26.539484  ]
 [58.64187121 17.00124233 60.21524816]]


In [210]:
# 生成区间随机整数数
arr = np.random.randint(1, 100, (2, 3))
print(arr)

[[11 34 86]
 [18 41 83]]


In [211]:
# 生成区间随机浮点数 （正态分布）
arr = np.random.randn(2, 3)
print(arr)

[[0.64703408 0.59321721 0.4380245 ]
 [1.35778902 1.20451128 1.35179619]]


In [212]:
# 设置随机数种子
np.random.seed(20)
arr = np.random.randint(1, 10, (2, 3))
print(arr)

[[4 5 7]
 [8 3 1]]


## 4. ndarray的数据类型

布尔类型 bool

整数类型 int uint   8~64位

浮点数 float   16~64位

复数 complex  32~64位

In [213]:
# 布尔类型
arr = np.array([1, 0, 2, 0], dtype = 'bool')
print(arr)

[ True False  True False]


In [214]:
# 整形
arr = np.array([1, 2, 3, 127], dtype = np.int8)
print(arr)

[  1   2   3 127]


## 5.索引与切片

### 一维数组的索引与切片

In [215]:
# 生成20个1~100随机整数
arr = np.random.randint(1, 100, 20)
print(arr)

[41 86 91 27 84 17 63 17  8 99  7 27 14 76 59 26  4 75 76 62]


In [216]:
print(arr[0], arr[1], arr[2])

41 86 91


In [217]:
print(arr[:3])  #前3个
print(arr[3:])  #3个之后的所有

[41 86 91]
[27 84 17 63 17  8 99  7 27 14 76 59 26  4 75 76 62]


In [218]:
print(arr[:-3])     #除去后3个
print(arr[-3:])     #后3个

[41 86 91 27 84 17 63 17  8 99  7 27 14 76 59 26  4]
[75 76 62]


In [219]:
print(arr[3:5])     #下标3~5之间两个，左闭右开

[27 84]


In [220]:
print(arr[5:3])     #反向索引为空

[]


In [221]:
print(arr[(arr > 50) & (arr < 80)])     #大于50小于80的元素

[63 76 59 75 76 62]


In [222]:
print(arr[slice(3, 5)])     #等价[3:5]
print(arr[slice(0, 20, 2)])     #0~20个元素之间，步长为2

[27 84]
[41 91 84 63  8  7 14 59  4 76]


### 二维数组的索引与切片

In [224]:
arr = np.random.randint(1, 100, (5, 5))     #1到100的5行5列的随机整数
print(arr)

[[78 84 58 95 33]
 [11  7 76 19  4]
 [78 18 44 17 19]
 [80 91 60 72 76]
 [30 46  7 64 79]]


In [225]:
print(arr[2, 2])    #下标2，2

44


In [226]:
# 下标2行，前3列
print(arr[:2, :3],"\n")
# 下标2行，后3列
print(arr[1, 2:])

[[78 84 58]
 [11  7 76]] 

[76 19  4]


In [227]:
# 下标1行，后4位
print(arr[1, -4:])
print(arr[1, 1:][arr[1, 1:] > 50])

[ 7 76 19  4]
[76]


In [228]:
# 取列
print(arr[:, 2])
print(arr[:, 2][arr[:, 2] > 50])

[58 76 44 60  7]
[58 76 60]
