# 一、 ndarray
## 1.ndarray的特性
### 多维性


In [60]:
import numpy as np

In [61]:
arr = np.array(5)   #创建零维ndarray数组，即常量
print(arr)
print(f'arr的维度：{arr.ndim}')     #获取维度

5
arr的维度：0


In [62]:
arr = np.array([1, 2, 3])   #创建零维ndarray数组，即常量
print(arr)
print(f'arr的维度：{arr.ndim}')     #获取维度

[1 2 3]
arr的维度：1


In [63]:
arr = np.array([[1, 2, 3], [4, 5, 6]])   #创建零维ndarray数组，即常量
print(arr)
print(f'arr的维度：{arr.ndim}')     #获取维度

[[1 2 3]
 [4 5 6]]
arr的维度：2


### 同质性

In [64]:
arr = np.array([1, 'hello'])    #不同数据类型会自动转换为相同类型
print(arr)

['1' 'hello']


In [65]:
arr = np.array([1, 2.5])    #不同数据类型会自动转换为相同类型
print(arr)

[1.  2.5]


## 2.ndarray的属性

In [66]:
arr = np.array(1)
print(arr)
print(f'arr的形状：{arr.shape}')
print(f'arr的维度：{arr.ndim}')
print(f'元素个数：{arr.size}')
print(f'元素类型：{arr.dtype}')
print(f'元素转置：{arr.T}')
print(f'单元素占用字节数：{arr.itemsize}')
print(f'数组总占用字节数：{arr.nbytes}')
print(f'内存存储方式(是否连续)：\n{arr.flags}')

1
arr的形状：()
arr的维度：0
元素个数：1
元素类型：int64
元素转置：1
单元素占用字节数：8
数组总占用字节数：8
内存存储方式(是否连续)：
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [67]:
arr = np.array([1, 2, 3])
print(arr)
print(f'arr的形状：{arr.shape}')
print(f'arr的维度：{arr.ndim}')
print(f'元素个数：{arr.size}')
print(f'元素类型：{arr.dtype}')
print(f'元素转置：{arr.T}')
print(f'单元素占用字节数：{arr.itemsize}')
print(f'数组总占用字节数：{arr.nbytes}')
print(f'内存存储方式(是否连续)：\n{arr.flags}')

[1 2 3]
arr的形状：(3,)
arr的维度：1
元素个数：3
元素类型：int64
元素转置：[1 2 3]
单元素占用字节数：8
数组总占用字节数：24
内存存储方式(是否连续)：
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [68]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(f'arr的形状：{arr.shape}')
print(f'arr的维度：{arr.ndim}')
print(f'元素个数：{arr.size}')
print(f'元素类型：{arr.dtype}')
print(f'元素转置：\n{arr.T}')
print(f'单元素占用字节数：{arr.itemsize}')
print(f'数组总占用字节数：{arr.nbytes}')
print(f'内存存储方式(是否连续)：\n{arr.flags}')

[[1 2 3]
 [4 5 6]]
arr的形状：(2, 3)
arr的维度：2
元素个数：6
元素类型：int64
元素转置：
[[1 4]
 [2 5]
 [3 6]]
单元素占用字节数：8
数组总占用字节数：48
内存存储方式(是否连续)：
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



## 3.ndarray的创建

In [69]:
# 基础创建方法
list = [1, 2, 3]
arr = np.array(list, dtype=np.float64)    #其实是传入一个列表,还可以指定类型
print(arr)

[1. 2. 3.]


In [70]:
# copy方法
arr1 = np.copy(arr)
print(arr1)

[1. 2. 3.]


### 预定义形状

In [71]:
# 全0
arr = np.zeros((2, 3))
print(arr)
print(f'默认类型：{arr.dtype}')

[[0. 0. 0.]
 [0. 0. 0.]]
默认类型：float64


In [72]:
# 全1
arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [73]:
# 未初始化
arr = np.empty((3, 3))
print(arr)

[[1.23075756e-312 7.63918485e-313 5.09278990e-313]
 [1.29441743e-312 4.24399159e-313 9.76118064e-313]
 [1.80369642e-312 1.29441743e-312 5.30498948e-313]]


In [74]:
# 固定值
arr = np.full((2, 3), 5)
print(arr)

[[5 5 5]
 [5 5 5]]


In [75]:
# 模仿
arr2 = np.zeros_like(arr)   #模仿arr的形状，生成全0
print(arr2)
arr2 = np.ones_like(arr)    #模仿arr的形状，生成全1
print(arr2)
arr2 = np.full_like(arr, 8) #模仿arr的形状，生成全8
print(arr2)
arr2 = np.empty_like(arr)   #模仿arr的形状，生成全随机
print(arr2)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[8 8 8]
 [8 8 8]]
[[1 1 1]
 [1 1 1]]


In [76]:
# 按步长
arr = np.arange(0, 10, 2)   #和range类似，左闭右开，步长为2
print(arr)

[0 2 4 6 8]


In [77]:
# 按数量取区间等间距
arr = np.linspace(0, 100, 5)     #此处左右闭合，等间距取5个数
print(arr)

[  0.  25.  50.  75. 100.]


In [78]:
# 对数步长
arr = np.logspace(0, 4, 3, base=2)
# 0  1  2  3  4
# ^     ^     ^
# 0到4之间取3个数，基底为2
#log2(1) = 0, log2(4) = 2, log2(16) = 4
print(arr)
# 其实最终得到的是等比数列

[ 1.  4. 16.]


In [79]:
# 再演示一个
arr = np.logspace(1, 5, 5, base=10)
print(arr)
#得到的就是1，10，100，1000，10000

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]


In [80]:
# 特殊矩阵
# 单位矩阵：主对角线上数字为1，其他数字为0
arr = np.eye(3, 4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [81]:
# 对角矩阵：主对角线非0，其他数字为0
arr = np.diag([1, 2, 3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [82]:
# 随机数组生成
# 生成0，1之间的随机浮点数
arr = np.random.rand(2, 3)
print(arr)

[[0.42101686 0.89977262 0.30895331]
 [0.70846117 0.55865405 0.32061787]]


In [83]:
# 生成区间随机浮点数
arr = np.random.uniform(1, 100, (2, 3))
print(arr)

[[ 5.43990474 28.06687041 91.72669095]
 [56.58648074 13.09093609 56.73789241]]


In [84]:
# 生成区间随机整数数
arr = np.random.randint(1, 100, (2, 3))
print(arr)

[[76 20 41]
 [76 71 98]]


In [85]:
# 生成区间随机浮点数 （正态分布）
arr = np.random.randn(2, 3)
print(arr)

[[ 0.50841746 -0.32490119  0.68349539]
 [ 0.92600296  0.22722706 -0.19685902]]


In [86]:
# 设置随机数种子
np.random.seed(20)
arr = np.random.randint(1, 10, (2, 3))
print(arr)

[[4 5 7]
 [8 3 1]]


## 4. ndarray的数据类型

布尔类型 bool

整数类型 int uint   8~64位

浮点数 float   16~64位

复数 complex  32~64位

In [87]:
# 布尔类型
arr = np.array([1, 0, 2, 0], dtype = 'bool')
print(arr)

[ True False  True False]


In [88]:
# 整形
arr = np.array([1, 2, 3, 127], dtype = np.int8)
print(arr)

[  1   2   3 127]


## 5.索引与切片

### 一维数组的索引与切片

In [89]:
arr = np.random.randint(1, 100, 20)
print(arr)

[41 86 91 27 84 17 63 17  8 99  7 27 14 76 59 26  4 75 76 62]


In [90]:
print(arr[0], arr[1], arr[2])

41 86 91


In [91]:
print(arr[:3])
print(arr[3:])

[41 86 91]
[27 84 17 63 17  8 99  7 27 14 76 59 26  4 75 76 62]


In [92]:
print(arr[:-3])
print(arr[-3:])

[41 86 91 27 84 17 63 17  8 99  7 27 14 76 59 26  4]
[75 76 62]


In [93]:
print(arr[3:5])

[27 84]


In [94]:
print(arr[5:3])

[]


In [95]:
print(arr[(arr > 50) & (arr < 80)])

[63 76 59 75 76 62]


In [96]:
print(arr[slice(3, 5)])
print(arr[slice(0, 20, 2)])

[27 84]
[41 91 84 63  8  7 14 59  4 76]


In [97]:
### 二维数组的索引与切片

In [99]:
arr = np.random.randint(1, 100, (5, 5))
print(arr)

[[25 19 94 34 79]
 [43 95  4 19 71]
 [53 23 15  5 28]
 [76  9  7 27 80]
 [83 79 11 34 86]]


In [101]:
print(arr[2, 2])

15


In [105]:
# 前2行，前3列
print(arr[:2, :3],"\n")
# 第2行，后3列
print(arr[1, 2:])

[[25 19 94]
 [43 95  4]] 

[ 4 19 71]


In [114]:
# 第1行，后4位
print(arr[1, -4:])
print(arr[1, 1:][arr[1, 1:] > 50])

[95  4 19 71]
[95 71]


In [115]:
# 取列
print(arr[:, 2])
print(arr[:, 2][arr[:, 2] > 50])

[94  4 15  7 11]
[94]
