numpy练习

In [1]:
from jedi.inference.compiled import access

'''
1.温度数据分析
某城市一周最高气温(摄氏度)为[28, 30, 29, 31, 32, 30, 29]
- 计算平均气温、最高气温和最低气温
- 找出气温超过30摄氏度的天数
'''

'\n1.温度数据分析\n某城市一周最高气温(摄氏度)为[28, 30, 29, 31, 32, 30, 29]\n- 计算平均气温、最高气温和最低气温\n- 找出气温超过30摄氏度的天数\n'

In [6]:
import numpy as np
temps = np.array([28, 30, 29, 31, 32, 30, 29])
print(f'平均气温：{np.mean(temps)}, 最高气温：{np.max(temps)}, 最低气温：{np.min(temps)}')
print(f'气温超过30摄氏度的天数：{len(temps[temps > 30])}')
print(f'气温超过30摄氏度的天数：{np.cumsum(np.where(temps > 30, 1, 0))[-1]}')
print(f'气温超过30摄氏度的天数：{np.count_nonzero(temps > 30)}')

平均气温：29.857142857142858, 最高气温：32, 最低气温：28
气温超过30摄氏度的天数：2
气温超过30摄氏度的天数：2
气温超过30摄氏度的天数：2


In [7]:
"""
2.学生成绩统计
某班级5名学生数学成绩分别为[85, 90, 78, 92, 88]
- 计算成绩的平均分、中位数和标准差
- 将成绩转换为百分制(满分为100分)
"""

'\n2.学生成绩统计\n某班级5名学生数学成绩分别为[85, 90, 78, 92, 88]\n- 计算成绩的平均分、中位数和标准差\n- 将成绩转换为百分制(满分为100分)\n'

In [12]:
scores = np.array([85, 90, 78, 92, 88])
print(f'平均分:{np.average(scores)}')
print(f'中位数:{np.median(scores)}')
print(f'标准差:{np.std(scores)}')

平均分:86.6
中位数:88.0
标准差:0.4882622246293481


In [13]:
"""
3.矩阵运算
给定矩阵 A = [[1, 2], [3, 4]]，B = [[5, 6], [7, 8]]
- 计算 A + B 和 A * B
- 计算 A 和 B 的矩阵乘法
"""

'\n3.矩阵运算\n给定矩阵 A = [[1, 2], [3, 4]]，B = [[5, 6], [7, 8]]\n- 计算 A + B 和 A * B\n- 计算 A 和 B 的矩阵乘法\n'

In [20]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(f'A + B:\n{A + B}')
print(f'A * B:\n{A * B}')
print(f'A @ B:\n{A @ B}')
print(f'A x B:\n{A.dot(B)}')

A + B:
[[ 6  8]
 [10 12]]
A * B:
[[ 5 12]
 [21 32]]
A @ B:
[[19 22]
 [43 50]]
A x B:
[[19 22]
 [43 50]]


In [21]:
"""
4.随机数生成
生成一个(3, 4)的随机整数数组, 范围[0, 10)
- 计算每列的最大值和每行的最小值
- 将数组中的所有奇数替换为 -1
"""

'\n4.随机数生成\n生成一个(3, 4)的随机整数数组, 范围[0, 10)\n- 计算每列的最大值和每行的最小值\n- 将数组中的所有奇数替换为 -1\n'